language: python
os:
  - linux
dist: bionic
python:
  - "3.6"
  - "3.7"
install:
  - sudo apt-get install libtesseract-dev libleptonica-dev tesseract-ocr tesseract-ocr-[rus]
  - pip install -r vision/requirements.txt
script:
  - bash vision/unit_tests/travis_runall.sh
